spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: app-user-manager

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
      register-with-eureka: true
      fetch-registry: true
server:
  port: 8080




